### PR TITLE
Add checkbox for reddit formatting.

### PR DESCRIPTION
**Pull request by joeheyming**
I added a button to copy to clipboard.
Then I added a checkbox that injects 4 spaces per line.

The way browsers do copy to clipboard is you have to call the
"select" function on a text input.

But in order to get the clipboard to have the 4 spaces, you have to
modify the text input value before calling select()

But I didn't want to confuse people, so I removed the 4
spaces after the copy function is complete.

### CODE REVIEW

**Comment by joeheyming** [comment]
Screen Shot 2019-08-10 at 5 17 52 PM

Formatted the text area with mono space font

**Comment by joeheyming** [comment]
Hey I wanted to improve ascii hypercube and I hope that you will accept my PR to make it format the text nicer in css and also have a way to format the text for reddit.

**Comment by 1j01** [comment]
Today I merged the changes and updated it to:
- Make the Copied to Clipboard indicator more prominent, and play well with screen readers
- Make the markdown formatting option independent of the copy to clipboard button; I think this makes it easier for the user to understand what the checkbox does, and this way they can copy directly from the textarea if they want.
- Tweak the media query split point, so input rows don't get wrapped near the split point
- Make the layout maximize available space by using flexbox instead of a 45% width (`calc(50% - Npx)` would also work but N would be dependent on the outside layout)

**Comment by 1j01** [comment]
> format the text nicer in css

1. It's not good to mix tabs and spaces in a project
2. It's not good to use *half tab stops* - this makes it so code editors can't deal with the indentation
3. If you want it to look nicer, set the tab width in your code editor.

**Comment by joeheyming** [comment]
Sorry about messing up your tabbing.
My company enforces 2 spaces over tabs.  I should have been more sensitive to this.

Thanks for accepting the changes.

**Pull request merged**
